In [1]:
import numpy as np

In [4]:
# 1
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# 2
arr = np.arange(9)
arr = arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# 3
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# 4
arr = np.arange(1,10).reshape(3,3)
i = np.eye(3)
m = np.dot(arr, i)
m

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
# 5
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = arr[arr % 2 != 0]
arr

array([1, 3, 5, 7, 9])

In [13]:
# 6
arr = np.arange(1,10)
arr[arr % 2 == 0] = -1
arr

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9])

In [15]:
# 7 
arr = np.arange(1,7)
arr = arr.reshape(3, 2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
# 8
arr = np.array([5, 2, 7, 1, 8, 4])
mean = np.mean(arr)
median = np.median(arr)
[mean, median]

[4.5, 4.5]

In [21]:
# 9
arr = np.array([12, 3, 45, 6, 78, 90, 23])
max = np.max(arr)
min = np.min(arr)
[max, min]

[90, 3]

In [22]:
# 10
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a, b)
c

32